### ISSUE TITLE
unstable reading tags

### ISSUE THREAD

**Issue by tokke100** [netsmarttech/node-red-contrib-cip-ethernet-ip#4]
I have setup the node to read a list of tags every second. It sometimes returns every 3 seconds, sometimes 3-4 times in the same second.

**Comment by gfcittolin** [comment]
Internally, the library performs the following activities in a loop:
 - perform a read of the tag group
 - perform a write of the tag group
 - waits the specified amount of time

So I'd expect that it could take a bit more time than the configured amount, mainly if there are a lot of tags, but not being faster than that. Also, please note that Node.JS (and therefore also Node-RED) is single-threaded, so if your flow is performing other blocking activities, it could affect the readings.

**Comment by gfcittolin** [comment]
Closing due to the lack of activity in the thread. Please feel free to reopen it if needed
