### ISSUE TITLE
Send array

### ISSUE THREAD

**Issue by GitHubAndDance** [netsmarttech/node-red-contrib-cip-ethernet-ip#9]
Does node-red-contrib-cip-ethernet-ip support sending an array of data using the "eth-ip out node" to an array on the PLC, or do i need to write to each individual "subtag" with individual nodes? 

If it does support it how should msg.payload be formatted?

**Comment by gfcittolin** [comment]
Good question, I don't remember trying it out with arrays. I'll check that out to see whether it works or not

**Comment by gfcittolin** [comment]
Just checked out, and unfortunately there's no support on the underlying library to directly address an array, just their members. They're currently in progress to add support to this (and other features, like support for strings), so we may benefit from it in the future.

**Comment by GitHubAndDance** [comment]
Thanks for answer

tir. d. 6. aug. 2019 18.53 skrev Guilherme Francescon <
notifications@github.com>:
